driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-7.9
    driver:
      cache_directory: false
  - name: debian-8.7
  - name: centos-6.8
    run_list:
      - recipe[yum::default]
  - name: centos-7.3
    run_list:
      - recipe[yum::default]

suites:
  - name: default
    run_list:
        - recipe[prometheus::default]
    attributes:

  - name: init
    run_list:
        - recipe[prometheus::default]
    provisioner:
        name: chef_zero
        require_chef_omnibus: 11.12.4
    attributes:
      prometheus:
        init_style: 'init'

  - name: bluepill
    run_list:
        - recipe[prometheus::default]
    attributes:
      prometheus:
        init_style: 'bluepill'

  - name: default-binary
    run_list:
        - recipe[prometheus::default]
    attributes:
      prometheus:
        install_method: 'binary'

  - name: init-binary
    run_list:
        - recipe[prometheus::default]
    attributes:
      prometheus:
        init_style: 'init'
        install_method: 'binary'
        flags:
          storage.remote.timeout: 45s

  - name: bluepill-binary
    run_list:
        - recipe[prometheus::default]
    attributes:
      prometheus:
        init_style: 'bluepill'
        install_method: 'binary'
