AllCops:
  Exclude:
    - vendor/**/*
    - .kitchen/**/*
    - Vagrantfile

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
NumericLiterals:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Metrics/LineLength:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
